# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Second_Window(object):
    def setupUi(self, Second_Window):
        Second_Window.setObjectName("Second_Window")
        Second_Window.resize(486, 300)
        Second_Window.setStyleSheet("font: 75 6pt \"Times New Roman\";")
        self.comboBox_2 = QtWidgets.QComboBox(Second_Window)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 10, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("font: 75 10pt \"Times New Roman\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(Second_Window)
        self.pushButton.setGeometry(QtCore.QRect(290, 10, 75, 23))
        self.pushButton.setStyleSheet("font: 75 10pt \"Times New Roman\";\n"
"background-color: rgb(57, 255, 3);\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Second_Window)
        QtCore.QMetaObject.connectSlotsByName(Second_Window)

    def retranslateUi(self, Second_Window):
        _translate = QtCore.QCoreApplication.translate
        Second_Window.setWindowTitle(_translate("Second_Window", "Form"))
        self.comboBox_2.setItemText(0, _translate("Second_Window", "Executed Sorting Processes"))
        self.comboBox_2.setItemText(1, _translate("Second_Window", "Insertion Sort"))
        self.comboBox_2.setItemText(2, _translate("Second_Window", "Selection Sort"))
        self.comboBox_2.setItemText(3, _translate("Second_Window", "Merge Sort"))
        self.comboBox_2.setItemText(4, _translate("Second_Window", "Bubble Sort"))
        self.comboBox_2.setItemText(5, _translate("Second_Window", "Quick Sort"))
        self.comboBox_2.setItemText(6, _translate("Second_Window", "Radix Sort"))
        self.comboBox_2.setItemText(7, _translate("Second_Window", "Counting Sort"))
        self.comboBox_2.setItemText(8, _translate("Second_Window", "Bucket Sort"))
        self.comboBox_2.setItemText(9, _translate("Second_Window", "Heap Sort"))
        self.comboBox_2.setItemText(10, _translate("Second_Window", "Gnome Sort"))
        self.comboBox_2.setItemText(11, _translate("Second_Window", "Comb Sort"))
        self.comboBox_2.setItemText(12, _translate("Second_Window", "Pigeonhole Sort"))
        self.comboBox_2.setItemText(13, _translate("Second_Window", "Shell Sort"))
        self.pushButton.setText(_translate("Second_Window", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_Window = QtWidgets.QWidget()
    ui = Ui_Second_Window()
    ui.setupUi(Second_Window)
    Second_Window.show()
    sys.exit(app.exec_())
